### ISSUE TITLE
Make it possible for servers.json to resolve hostnames

### ISSUE THREAD

**Issue by Anjum9694** [FICTURE7/uberstrok#25]
If anyone with a dynamic IP wants to host a gameserver they will encounter this issue because right now the comm and gameserver portion of the file only accepts IP addresses instead of hostnames.

Every time the router restarts the IP address will be renewed thus have to update the server.json manually.

When a hostname is used the Uberstrike game shows Server is not reachable. The same hostname but as an IP address works.

**Comment by FICTURE7** [comment]
That is a neat idea, should definitely be implemented.

**Comment by recreationx** [comment]
I tried to implement it, you can view it at
https://github.com/recreationx/uberstrok/blob/v0.1.x/src/UberStrok.WebServices/ServerManager.cs
Works on my machine (using no-ip as a host provider), just build Uberstrok.WebServices with the above code and then test it our yourself.

**Comment by Anjum9694** [comment]
Confirmed solution provided by @recreationx works.
