### ISSUE TITLE
Running a gameserver

### ISSUE THREAD

**Issue by recreationx** [FICTURE7/uberstrok#26]
I successfully built everything and set everything up running, but I encountered a problem when trying to allow my friends to join.
What I did:
1. Port forward 5055 and 5056 (UDP) on my router
2. Changed servers.json and main.json to fit my server
3. Changed contents of .uberstrok to http://mypublicip/2.0/
4. Allowed ports through firewall, enabled auto-detect public ip in Photon server

However I am still unable to find a running server on ports 5055 and 5056 when using a port checker. Ran the files on another pc and it was unable to connect too.

Any help? Much appreciated.

**Comment by FICTURE7** [comment]
Make sure `UberStrok.WebServices` is running and can be accessed through your external IP on port 80 (TCP). Maybe the port checker you used tests TCP only, if it does, try using a UDP port checker to check for 5055 and 5056. Also very important the `.uberstrok` file must not contain any new lines or trailing whitespaces

**Comment by Anjum9694** [comment]
Photon ports can only be accessed remotely with an authenticated Uberstrike client. It is normal for a port checker to show those as closed. Don't forget you will have to port forward 80 too!

**Comment by FICTURE7** [comment]
Closing this, since you seemed to have it figured out. Re-open it if I was wrong. :>
