### ISSUE TITLE
Access Level Codes

### ISSUE THREAD

**Issue by Anjum9694** [FICTURE7/uberstrok#31]
Working Directory `UberStrok.WebServices\bin\Release\data\profiles\*.json`

If anyone knows the remaining codes list it down in this issue.

**So far known Access Levels:** 
Normal Player `0`
Administrator `10`

**Comment by recreationx** [comment]
Default `0`
QA `3`
Moderator `4`
Senior QA `6`
Senior Moderator `7`
Admin `10`

Try it out for yourself to be sure.
